from __future__ import unicode_literals

"""
List of countries that Spotify is available in.

The list is based on:
https://support.spotify.com/us/learn-more/faq/#!/article/Availability-in-overseas-territories

Last updated: 2015-01-22
"""
COUNTRIES = {
    'AD': 'Andorra',
    'AR': 'Argentina',
    'AU': 'Australia',
    'AT': 'Austria',
    'BE': 'Belgium',
    'BO': 'Bolivia',
    'BR': 'Brazil',
    'BG': 'Bulgaria',
    'CA': 'Canada',
    'CL': 'Chile',
    'CO': 'Colombia',
    'CR': 'Costa Rica',
    'CY': 'Cyprus',
    'CZ': 'Czech Republic',
    'DK': 'Denmark',
    'DO': 'Dominican Republic',
    'EC': 'Ecuador',
    'SV': 'El Salvador',
    'EE': 'Estonia',
    'FI': 'Finland',
    'FR': 'France',
    'DE': 'Germany',
    'GR': 'Greece',
    'GT': 'Guatemala',
    'HN': 'Honduras',
    'HK': 'Hong Kong',
    'HU': 'Hungary',
    'IS': 'Iceland',
    'IE': 'Ireland',
    'IT': 'Italy',
    'LV': 'Latvia',
    'LI': 'Liechtenstein',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'MY': 'Malaysia',
    'MX': 'Mexico',
    'MC': 'Monaco',
    'NL': 'Netherlands',
    'NZ': 'New Zealand',
    'NI': 'Nicaragua',
    'NO': 'Norway',
    'PA': 'Panama',
    'PY': 'Paraguay',
    'PE': 'Peru',
    'PH': 'Philipines',
    'PL': 'Poland',
    'PT': 'Portugal',
    'SG': 'Singapore',
    'SK': 'Slovakia',
    'ES': 'Spain',
    'SE': 'Sweden',
    'CH': 'Switzerland',
    'TW': 'Taiwan',
    'TR': 'Turkey',
    'GB': 'United Kingdom',
    'US': 'United States',
    'UY': 'Uruguay',
}
